function F = analysis_info(figdata)
% info = analysis_info(figdata) - an interactive GUI for user to specify
% parameters for analysis before analysis is launched

%defaults
nostimtype = 0;
if ~isempty(figdata)
    fnames = fieldnames(figdata);
    if ismember('stimtype', fnames)
        info.stimtype = figdata.stimtype;
    else
        nostimtype = 1;
    end
%     switch hrf.setup
%         case 'ao'
%             info.stimtype = '13.5s_gray60Hz';
%         otherwise
%             info.stimtype = '8s_gray60Hz';
%     end
end
% info.stimtype = '8s_gray60Hz';
info.tostitch = 1;
info.dffmethod = 'Median';
info.bgmethod = 'staticpixels';
info.bgcorrmethod = 'linear';

%colors
cbg = html2rgb('#9fb1bc');
cbuttonlabel = html2rgb('#e2c044');
cbig = html2rgb('#d3d0cb');
cbutton = html2rgb('#6e8898');
csmall = html2rgb('#2e5266');
C.bg_col = cbg;
C.big_font = cbig;
C.small_font = csmall;
C.button = cbutton;
C.button_label = cbuttonlabel;


%figure
F = figure;
set(F,'units', 'normalized', 'position', [0.343 0.332 0.403 0.326],...
    'Color',C.bg_col,'MenuBar','None','numbertitle','off','Name','Paremeter selection',...
    'WindowStyle','modal');

%GUI ELEMENTS

%STIMTYPE
RBgroup1 = uibuttongroup(F,'Visible','off',...
    'Position',[0.0 0.25 0.25 0.7],...
    'BackgroundColor',C.bg_col,...
    'Units','Normalized','BorderType','None','FontSize',14,...
    'fontweight','bold','TitlePosition','LeftTop',...
    'Title','Stim Type','foregroundcolor',C.big_font,...
    'SelectionChangedFcn',@stimselection);
RB1(1) = uicontrol(RBgroup1,'Style',...
    'radiobutton',...
    'String','8s_gray60Hz','units','normalized','BackgroundColor',C.bg_col,...
    'FontSize',10,'foregroundcolor',C.small_font,'Position',[0.1 0.7 0.8 0.3],...
    'HandleVisibility','on');

RB1(2) = uicontrol(RBgroup1,'Style','radiobutton',...
    'String','13.5s_gray60Hz','units','normalized',...
    'Position',[0.1 0.5 0.8 0.3],'BackgroundColor',C.bg_col,...
    'FontSize',10,'foregroundcolor',C.small_font,'HandleVisibility','on');

RB1(3) = uicontrol(RBgroup1,'Style','radiobutton',...
    'String','14s_gray60Hz','units','normalized',...
    'Position',[0.1 0.3 0.8 0.3],'BackgroundColor',C.bg_col,...
    'FontSize',10,'foregroundcolor',C.small_font,'HandleVisibility','on');
if isempty(figdata) && nostimtype
    RBgroup1.Visible = 'on';
end

if ~isempty(figdata)
    switch figdata.setup
        case 'ao'
            set(RB1(2),'Value',1);
        otherwise
            set(RB1(1),'Value',1);
    end
end

%STITCHING
RBgroup2 = uibuttongroup(F,'Visible','off',...
    'Position',[0.2 0.25 0.25 0.7],...
    'BackgroundColor',C.bg_col,...
    'Units','Normalized','BorderType','None','FontSize',14,...
    'fontweight','bold','TitlePosition','LeftTop',...
    'Title','Stitching','foregroundcolor',C.big_font,...
    'SelectionChangedFcn',@tostitch);
RB2(1) = uicontrol(RBgroup2,'Style',...
    'radiobutton',...
    'String','Stitch','units','normalized','BackgroundColor',C.bg_col,...
    'FontSize',10,'foregroundcolor',C.small_font,'Position',[0.1 0.7 0.8 0.3],...
    'HandleVisibility','on');

RB2(2) = uicontrol(RBgroup2,'Style','radiobutton',...
    'String','Dont stitch','units','normalized',...
    'Position',[0.1 0.5 0.8 0.3],'BackgroundColor',C.bg_col,...
    'FontSize',10,'foregroundcolor',C.small_font,'HandleVisibility','on');
RBgroup2.Visible = 'on';
set(RB2(1),'Value',1);


%DFF METHOD
RBgroup3 = uibuttongroup(F,'Visible','off',...
    'Position',[0.4 0.25 0.25 0.7],...
    'BackgroundColor',C.bg_col,...
    'Units','Normalized','BorderType','None','FontSize',14,...
    'fontweight','bold','TitlePosition','LeftTop',...
    'Title','Dff Method','foregroundcolor',C.big_font,...
    'SelectionChangedFcn',@dffmethod);
RB3(1) = uicontrol(RBgroup3,'Style',...
    'radiobutton',...
    'String','Median','units','normalized','BackgroundColor',C.bg_col,...
    'FontSize',10,'foregroundcolor',C.small_font,'Position',[0.1 0.8 0.8 0.1],...
    'HandleVisibility','on');

RB3(2) = uicontrol(RBgroup3,'Style','radiobutton',...
    'String','Mode','units','normalized',...
    'Position',[0.1 0.7 0.8 0.1],'BackgroundColor',C.bg_col,...
    'FontSize',10,'foregroundcolor',C.small_font,'HandleVisibility','on');

RB3(3) = uicontrol(RBgroup3,'Style','radiobutton',...
    'String','Percentile','units','normalized',...
    'Position',[0.1 0.6 0.8 0.1],'BackgroundColor',C.bg_col,...
    'FontSize',10,'foregroundcolor',C.small_font,'HandleVisibility','on');

RB3(4) = uicontrol(RBgroup3,'Style','radiobutton',...
    'String','Gauss','units','normalized',...
    'Position',[0.1 0.5 0.8 0.1],'BackgroundColor',C.bg_col,...
    'FontSize',10,'foregroundcolor',C.small_font,'HandleVisibility','on');

RB3(5) = uicontrol(RBgroup3,'Style','radiobutton',...
    'String','Mean','units','normalized',...
    'Position',[0.1 0.4 0.8 0.1],'BackgroundColor',C.bg_col,...
    'FontSize',10,'foregroundcolor',C.small_font,'HandleVisibility','on');

RB3(6) = uicontrol(RBgroup3,'Style','radiobutton',...
    'String','onAcid','units','normalized',...
    'Position',[0.1 0.3 0.8 0.1],'BackgroundColor',C.bg_col,...
    'FontSize',10,'foregroundcolor',C.small_font,'HandleVisibility','on');

RBgroup3.Visible = 'on';

%BG method
RBgroup4 = uibuttongroup(F,'Visible','off',...
    'Position',[0.6 0.25 0.25 0.7],...
    'BackgroundColor',C.bg_col,...
    'Units','Normalized','BorderType','None','FontSize',14,...
    'fontweight','bold','TitlePosition','LeftTop',...
    'Title','BG Method','foregroundcolor',C.big_font,...
    'SelectionChangedFcn',@bgmethod);
RB4(1) = uicontrol(RBgroup4,'Style',...
    'radiobutton',...
    'String','static pixels','units','normalized','BackgroundColor',C.bg_col,...
    'FontSize',10,'foregroundcolor',C.small_font,'Position',[0.1 0.7 0.8 0.3],...
    'HandleVisibility','on');

RB4(2) = uicontrol(RBgroup4,'Style','radiobutton',...
    'String','dynamic pixels','units','normalized',...
    'Position',[0.1 0.5 0.8 0.3],'BackgroundColor',C.bg_col,...
    'FontSize',10,'foregroundcolor',C.small_font,'HandleVisibility','on');

RB4(3) = uicontrol(RBgroup4,'Style','radiobutton',...
    'String','all outside','units','normalized',...
    'Position',[0.1 0.3 0.8 0.3],'BackgroundColor',C.bg_col,...
    'FontSize',10,'foregroundcolor',C.small_font,'HandleVisibility','on');

RB4(4) = uicontrol(RBgroup4,'Style','radiobutton',...
    'String','skip','units','normalized',...
    'Position',[0.1 0.1 0.8 0.3],'BackgroundColor',C.bg_col,...
    'FontSize',10,'foregroundcolor',C.small_font,'HandleVisibility','on');
RBgroup4.Visible = 'on';

%BG CORRR METHOD
RBgroup5 = uibuttongroup(F,'Visible','off',...
    'Position',[0.78 0.25 0.25 0.7],...
    'BackgroundColor',C.bg_col,...
    'Units','Normalized','BorderType','None','FontSize',14,...
    'fontweight','bold','TitlePosition','LeftTop',...
    'Title','BG Corr Method','foregroundcolor',C.big_font,...
    'SelectionChangedFcn',@bgcorrmethod);
RB5(1) = uicontrol(RBgroup5,'Style',...
    'radiobutton',...
    'String','Linear','units','normalized','BackgroundColor',C.bg_col,...
    'FontSize',10,'foregroundcolor',C.small_font,'Position',[0.1 0.7 0.8 0.3],...
    'HandleVisibility','on');

RB5(2) = uicontrol(RBgroup5,'Style','radiobutton',...
    'String','Contamination r','units','normalized',...
    'Position',[0.1 0.5 0.8 0.3],'BackgroundColor',C.bg_col,...
    'FontSize',10,'foregroundcolor',C.small_font,'HandleVisibility','on');

RB5(3) = uicontrol(RBgroup5,'Style','radiobutton',...
    'String','Custom AO','units','normalized',...
    'Position',[0.1 0.3 0.8 0.3],'BackgroundColor',C.bg_col,...
    'FontSize',10,'foregroundcolor',C.small_font,'HandleVisibility','on');
RBgroup5.Visible = 'on';
set(RB5(1),'Value',1);


PB(1) = uicontrol(F,'Style', 'Pushbutton', 'String', 'CONFIRM',...
    'Units','Normalized','Position', [0.4 0.1 0.2 0.2],...
    'background',C.button,'ForegroundColor',C.button_label,'FontSize',14,'fontweight','bold',...
    'Callback', @local_confirm,'Tag','confirm');

d.F = F;
d.info = info;
guidata(F,d);


function cc = html2rgb(code)
cc = sscanf(code(2:end),'%2x%2x%2x',[1 3])/255;

function stimselection (hObject, eventdata)
d = guidata(hObject);
choice = eventdata.NewValue.String;
d.info.stimtype = lower(choice);
guidata(d.F,d);

function tostitch (hObject, eventdata)
d = guidata(hObject);
choice = eventdata.NewValue.String;
switch choice
    case 'Stitch'
        d.info.tostitch = 1;
    case 'Dont stitch'
        d.info.tostitch = 0;
end

guidata(d.F,d);

function dffmethod (hObject, eventdata)
d = guidata(hObject);
choice = eventdata.NewValue.String;
d.info.dffmethod = choice;
guidata(d.F,d);

function bgmethod (hObject, eventdata)
d = guidata(hObject);
choice = eventdata.NewValue.String;
choice = choice(~isspace(choice));
d.info.bgmethod = choice;
guidata(d.F,d);

function bgcorrmethod (hObject, eventdata)
d = guidata(hObject);
choice = eventdata.NewValue.String;
choice = lower(choice(~isspace(choice)));
d.info.bgcorrmethod = choice;
guidata(d.F,d);

function local_confirm (hObject, eventdata)
d = guidata(hObject);
try
    h5cre = findobj('Tag','h5creator');
    dh5cre = guidata(h5cre);
    dh5cre.info = d.info;
    guidata(dh5cre.F, dh5cre);
    disp('Info struct embedded to H5creator.');
catch
    disp('H5creator was not found in environment. Info struct was not embedded.');
end
info = d.info;
assignin('base','info',info);
close(d.F);
